import { AlertTriangle } from "lucide-react";

export function MedicalDisclaimer() {
  return (
    <section className="border-b border-border bg-accent/5 py-10">
      <div className="mx-auto max-w-3xl px-4 text-center md:px-6">
        <div className="flex items-center justify-center gap-2">
          <AlertTriangle className="h-5 w-5 shrink-0 text-accent" />
          <h3 className="text-sm font-semibold uppercase tracking-wide text-accent">
            Medical Disclaimer
          </h3>
        </div>
        <p className="mt-3 text-sm leading-relaxed text-muted-foreground">
          This tool is <strong className="text-foreground">NOT</strong> a
          substitute for professional medical advice, diagnosis, or treatment.
          Always consult a licensed physician for any medical concerns. Results
          generated by our AI model are for informational purposes only and
          should not be used as the sole basis for any medical decisions.
        </p>
      </div>
    </section>
  );
}
